### PR TITLE
Drop `node_modules` and `.DS_Store`, update `.gitignore` to exclude personal vscode settings

### LINKED ISSUE #42: Add a `.gitignore`
I don't believe `.DS_Store`, `node_modules`, nor `.vscode` are intended to be in the `main` branch of the repo, but correct me if I'm wrong!

Happy to open a PR to resolve if wanted.

### PR DESCRIPTION
**Pull request by rijkvanzanten**
Fixes #42

### CODE REVIEW

**Comment by chadwhitacre** [comment]
Kind of a bummer that we have `node_modules` bloating our Git history forever. Sorry for not catching that sooner. I did notice that #25 included hundreds of thousands of files but we were moving fast ahead of launch, didn't want to slow us down. 😖

@rijkvanzanten Can you inspect our GitHub deploy action and confirm that we don't need `node_modules` to be checked in for the build and deploy to work for some reason?

**Comment by rijkvanzanten** [comment]
> Kind of a bummer that we have node_modules bloating our Git history forever.

I believe there's a way to purge that from the history forever, but am a little hesitant to go ahead with that as it would rewrite the history of `main` and might cause issues with other forks or local copies that need to be updated..

> Can you inspect our GitHub deploy action and confirm that we don't need node_modules to be checked in for the build and deploy to work for some reason?

https://github.com/fairsource/fair.io/blob/2eb2f80fa581dc6f4af109bda113620758d34575/.github/workflows/deploy.yml#L66-L74

As far as I can tell, your workflow is installing the dependencies using the detected package manager (which would be `npm` in this case) before building the website 👍🏻

**Comment by chadwhitacre** [comment]
> it would rewrite the history

Yeah, don't want to go that route at this point. :-/

Thanks for validating the workflow. Merging! 💃

**Comment by chadwhitacre** [comment]
Thanks for the PR, @rijkvanzanten ! 🎉

**Comment by williamtheaker** [comment]
`.DS_Store` is still in the main branch btw

**Comment by chadwhitacre** [comment]
PR? 🙃

**Comment by ElioDiNino** [comment]
> PR? 🙃

#57

**Pull request merged**
