### PR TITLE
Add ptah.sh

### LINKED ISSUE #37: Add Ptah.sh to the companies who love FSL
Hey. :)

It seems to be enough motivation for me to jump straight into publishing an article. :D

image

This is the link to the publication:
https://ptah.sh/blog/2024-08-09-we-use-fair-source/

This the announcement on the company's social page:
https://x.com/ptah_sh/status/1821894028838723991

### PR DESCRIPTION
**Pull request by chadwhitacre**
Closes #37.

Screenshot 2024-08-09 at 1 10 43 PM

Screenshot 2024-08-09 at 1 10 37 PM

### CODE REVIEW

**Comment by bohdan-shulha** [comment]
Incredible. Thank you!

image

**Comment by chadwhitacre** [comment]
Awesome! Will wait for @ezekg to approve as well and then we can merge. 👍

**Review by ezekg — APPROVED** [review]
Looks good! LGTM. Thanks for joining us on this adventure!

**Comment by chadwhitacre** [comment]
🥳 💃 😁 🙇‍♂️

**Pull request merged**
